// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomanianBurgerWeb.Data;

#nullable disable

namespace RBweb.Migrations
{
    [DbContext(typeof(RomanianBurgerWebContext))]
    [Migration("20260214102329_AddCategoryName")]
    partial class AddCategoryName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RBweb.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("RBweb.Models.Meniu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataAdaugare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Meniu");
                });

            modelBuilder.Entity("RBweb.Models.MeniuCategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int>("MeniuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("MeniuID");

                    b.ToTable("MeniuCategorie");
                });

            modelBuilder.Entity("RBweb.Models.MeniuCategorie", b =>
                {
                    b.HasOne("RBweb.Models.Categorie", "Categorie")
                        .WithMany("MeniuCategorii")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RBweb.Models.Meniu", "Meniu")
                        .WithMany("MeniuCategorii")
                        .HasForeignKey("MeniuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Meniu");
                });

            modelBuilder.Entity("RBweb.Models.Categorie", b =>
                {
                    b.Navigation("MeniuCategorii");
                });

            modelBuilder.Entity("RBweb.Models.Meniu", b =>
                {
                    b.Navigation("MeniuCategorii");
                });
#pragma warning restore 612, 618
        }
    }
}
